"use server";
import { redirect } from "next/navigation";import { Resend } from "resend";import { createSupabaseAdminClient } from "@/lib/supabase/admin";import { requireStayUser } from "@/lib/stay/auth";import { SITE_URL } from "@/config/site";
export type BookingState={success:boolean;message:string};
export type BookingQuote={nights:number;guestCount:number;subtotal:number;additionalGuestFee:number;discountAmount:number;cleaningFee:number;totalAmount:number;lengthDiscountLabel:string;lengthDiscountRate:number};
const val=(f:FormData,n:string,max:number)=>{const x=f.get(n);return typeof x==="string"&&x.trim().length<=max?x.trim():null};
function toBookingQuote(value:unknown):BookingQuote|null{if(!value||typeof value!=="object")return null;const q=value as Record<string,unknown>;return{nights:Number(q.nights),guestCount:Number(q.guestCount),subtotal:Number(q.subtotal),additionalGuestFee:Number(q.additionalGuestFee),discountAmount:Number(q.discountAmount),cleaningFee:Number(q.cleaningFee),totalAmount:Number(q.totalAmount),lengthDiscountLabel:String(q.lengthDiscountLabel??""),lengthDiscountRate:Number(q.lengthDiscountRate??0)}}
export async function recalculateStayPrice(listingId:string,checkIn:string,checkOut:string,guests:number):Promise<BookingQuote>{await requireStayUser();if(!/^[0-9a-f-]{36}$/i.test(listingId)||!/^\d{4}-\d{2}-\d{2}$/.test(checkIn)||!/^\d{4}-\d{2}-\d{2}$/.test(checkOut)||!Number.isInteger(guests)||guests<1)throw new Error("料金を再計算できませんでした。");const {data,error}=await createSupabaseAdminClient().rpc("calculate_stay_price",{p_listing_id:listingId,p_check_in:checkIn,p_check_out:checkOut,p_guest_count:guests,p_discount:0});const quote=toBookingQuote(data);if(error||!quote||Object.values(quote).some(value=>typeof value==="number"&&!Number.isFinite(value))){console.error("宿泊料金の再計算に失敗しました。",error);throw new Error("料金を再計算できませんでした。")}return quote}
export async function notify(bookingId:string,customerId:string,email:string,name:string,number:string,subject?:string,text?:string){const admin=createSupabaseAdminClient();const defaultSubject=`【SK EC Pro】予約リクエストを受け付けました（${number}）`;const defaultText=`${name} 様\n\n予約リクエストを受け付けました。内容を確認後、メールでお知らせします。\n${SITE_URL}/stay/mypage/bookings/${bookingId}`;const recipients=[{to:email,type:"booking_received_customer",subject:subject??defaultSubject,text:text??defaultText},{to:process.env.STAY_ADMIN_NOTIFICATION_EMAIL??process.env.RESEND_FROM_EMAIL??"",type:"booking_requested_admin",subject:`【SK EC Pro】新しい宿泊予約申請（${number}）`,text:`新しい宿泊予約申請があります。\n${SITE_URL}/admin/stay/bookings/${bookingId}`}];for(const item of recipients){if(!item.to)continue;let status="failed",errorMessage:string|null="メール設定がありません。",sentAt:string|null=null;const key=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL;if(key&&from){const {error}=await new Resend(key).emails.send({from,to:[item.to],subject:item.subject,text:item.text});if(!error){status="sent";errorMessage=null;sentAt=new Date().toISOString()}else errorMessage=error.message}await admin.from("stay_notifications").insert({booking_id:bookingId,customer_id:customerId,notification_type:item.type,recipient:item.to,status,error_message:errorMessage,sent_at:sentAt})}}
export async function requestBooking(_s:BookingState,formData:FormData):Promise<BookingState>{const {customer,supabase}=await requireStayUser();const listingId=val(formData,"listingId",36),checkIn=val(formData,"checkIn",10),checkOut=val(formData,"checkOut",10),name=val(formData,"name",100),email=val(formData,"email",254),phone=val(formData,"phone",30),arrival=val(formData,"arrivalTime",5),purpose=val(formData,"purpose",500),note=val(formData,"note",2000),requests=val(formData,"requests",2000),guests=Number(formData.get("guests"));if(!listingId||!checkIn||!checkOut||!name||!email||!phone||!arrival||!Number.isInteger(guests))return{success:false,message:"必須項目を正しく入力してください。"};const {data:id,error}=await supabase.rpc("create_stay_booking",{p_listing_id:listingId,p_check_in:checkIn,p_check_out:checkOut,p_guest_count:guests,p_name:name,p_email:email,p_phone:phone,p_arrival_time:arrival,p_purpose:purpose??"",p_note:note??"",p_requests:requests??"",p_airbnb:formData.get("airbnb")==="on"});if(error||!id){console.error("宿泊予約申請に失敗しました。",error);const msg=error?.message.includes("unavailable")||error?.message.includes("blocked")?"選択された期間は予約できません。":"予約を受け付けられませんでした。入力内容を確認してください。";return{success:false,message:msg}}const admin=createSupabaseAdminClient();const {data:booking}=await admin.from("stay_bookings").select("booking_number").eq("id",id).single();if(booking)await notify(id,customer.id,email,name,booking.booking_number).catch(e=>console.error("宿泊予約通知に失敗しました。",e));redirect(`/stay/mypage/bookings/${id}?created=1`)}
