"use client";

import Image from "next/image";
import { useActionState } from "react";
import { ImagePlus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { deleteEstimateItemImage, updateEstimateItem, uploadEstimateItemImages, type UpdateEstimateState } from "./actions";

type ImageView = { id: string; url: string; originalName: string };
type Item = { id: string; url: string; productName: string; color: string; size: string; model: string; request: string };
const initial: UpdateEstimateState = { success: false, message: "" };

function ImageSection({ estimateId, itemId, type, images, limit }: { estimateId: string; itemId: string; type: "estimate" | "received"; images: ImageView[]; limit: number }) {
  const [state, action, pending] = useActionState(uploadEstimateItemImages, initial);
  const label = type === "received" ? "中国物流に届いた商品の画像" : "見積商品の画像";
  return <section className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-bold">{label}</h4><p className="mt-1 text-xs text-slate-400">最大{limit}枚・1回2枚まで・jpg/png/webp・1枚10MB</p></div><span className="text-xs font-semibold text-slate-400">{images.length}/{limit}</span></div>{images.length > 0 && <div className="mt-4 grid grid-cols-3 gap-3 sm:grid-cols-5">{images.map((image) => <div key={image.id} className="group relative aspect-square overflow-hidden rounded-lg border border-slate-200 bg-white"><Image src={image.url} alt={image.originalName} fill unoptimized className="object-cover" /><form action={deleteEstimateItemImage} className="absolute right-1 top-1"><input type="hidden" name="estimateId" value={estimateId} /><input type="hidden" name="imageId" value={image.id} /><input type="hidden" name="imageType" value={type} /><button type="submit" className="grid size-7 place-items-center rounded-full bg-red-600 text-white" aria-label={`${image.originalName}を削除`}><Trash2 size={13} /></button></form></div>)}</div>}<form action={action} className="mt-4"><input type="hidden" name="estimateId" value={estimateId} /><input type="hidden" name="itemId" value={itemId} /><input type="hidden" name="imageType" value={type} /><label className="flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-emerald-300 bg-white px-4 text-sm font-semibold text-emerald-700"><ImagePlus size={17} />画像を選択<input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" disabled={pending || images.length >= limit} /></label><Button type="submit" size="sm" className="mt-3" disabled={pending || images.length >= limit}>{pending ? "アップロード中…" : "選択画像を追加"}</Button>{state.message && <p className={`mt-2 text-xs ${state.success ? "text-emerald-700" : "text-red-600"}`}>{state.message}</p>}</form></section>;
}

export function EstimateItemEditor({ estimateId, item, estimateImages, receivedImages }: { estimateId: string; item: Item; estimateImages: ImageView[]; receivedImages: ImageView[] }) {
  const [state, action, pending] = useActionState(updateEstimateItem, initial);
  const input = "h-10 rounded-md border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20";
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><form action={action}><input type="hidden" name="estimateId" value={estimateId} /><input type="hidden" name="itemId" value={item.id} /><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium sm:col-span-2">商品名<input name="productName" defaultValue={item.productName} maxLength={300} className={input} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">商品URL<input name="url" type="url" defaultValue={item.url} maxLength={2000} className={input} /></label><label className="grid gap-2 text-sm font-medium">色<input name="color" defaultValue={item.color} maxLength={200} className={input} /></label><label className="grid gap-2 text-sm font-medium">サイズ<input name="size" defaultValue={item.size} maxLength={200} className={input} /></label><label className="grid gap-2 text-sm font-medium">型番<input name="model" defaultValue={item.model} maxLength={200} className={input} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">その他・希望内容<textarea name="request" defaultValue={item.request} maxLength={2000} rows={4} className={`${input} h-auto py-2`} /></label></div><div className="mt-4 flex items-center gap-3"><Button type="submit" disabled={pending}><Save size={16} />{pending ? "保存中…" : "商品情報を保存"}</Button>{state.message && <p className={`text-sm ${state.success ? "text-emerald-700" : "text-red-600"}`}>{state.message}</p>}</div></form><div className="mt-6 grid gap-4 lg:grid-cols-2"><ImageSection estimateId={estimateId} itemId={item.id} type="estimate" images={estimateImages} limit={10} /><ImageSection estimateId={estimateId} itemId={item.id} type="received" images={receivedImages} limit={2} /></div></article>;
}
