"use server";import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { requireAdminUser } from "@/lib/auth/require-admin";import { createSupabaseAdminClient } from "@/lib/supabase/admin";import { syncStayCalendarFeedById,validatedAirbnbCalendarUrl } from "@/lib/stay/calendar-sync";import { notify } from "@/app/stay/book/[listingId]/actions";import { SITE_URL } from "@/config/site";
const text=(f:FormData,n:string,max=2000)=>String(f.get(n)??'').trim().slice(0,max);const num=(f:FormData,n:string)=>Math.max(0,Number(f.get(n))||0);
export async function updateStayBooking(formData:FormData){
  const user=await requireAdminUser();
  const id=text(formData,'id',36),status=text(formData,'status',50),requestedPaymentStatus=text(formData,'paymentStatus',50),paymentMethod=text(formData,'paymentMethod',50),previous=text(formData,'previousStatus',50),previousCheckIn=text(formData,'previousCheckIn',10),previousCheckOut=text(formData,'previousCheckOut',10),checkIn=text(formData,'checkIn',10),checkOut=text(formData,'checkOut',10);
  
  const paymentStatus=status==='paid'?'paid':requestedPaymentStatus;
  const allowed=['pending_admin_review','admin_reviewing','awaiting_guest_confirmation','confirmed','payment_pending','paid','check_in_scheduled','checked_in','checked_out','completed','guest_cancelled','admin_cancelled','expired','no_show'];
  const allowedPaymentStatuses=['unpaid','payment_pending','paid','refunded','partially_refunded'];
  const allowedPaymentMethods=['','bank_transfer','stripe_card','cash','card_manual','other'];
  
  // More robust date validation
  const isValidDate = (dateStr: string) => {
    if (!dateStr || typeof dateStr !== 'string') return false;
    // Check if it matches YYYY-MM-DD format
    if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return false;
    // Try to parse the date
    const date = new Date(dateStr);
    // Check if it's a valid date
    return !isNaN(date.getTime());
  };
  
  // For date comparison, we need to ensure we're comparing just the date parts
  const compareDates = (date1Str: string, date2Str: string) => {
    const date1 = new Date(date1Str);
    const date2 = new Date(date2Str);
    // Reset time parts to compare just dates
    date1.setHours(0, 0, 0, 0);
    date2.setHours(0, 0, 0, 0);
    return date2 > date1;
  };
  
  const checkInValid = isValidDate(checkIn);
  const checkOutValid = isValidDate(checkOut);
  const datesValid = checkInValid && checkOutValid && compareDates(checkIn, checkOut);
  
  const allValidationPassed = allowed.includes(status) && 
                             allowedPaymentStatuses.includes(paymentStatus) && 
                             allowedPaymentMethods.includes(paymentMethod) && 
                             datesValid;
  
  if(!allValidationPassed)redirect(`/admin/stay/bookings/${id}?saved=invalid`);
  const transitions:Record<string,string[]>={pending_admin_review:['admin_reviewing','awaiting_guest_confirmation','admin_cancelled','expired'],admin_reviewing:['awaiting_guest_confirmation','admin_cancelled','expired'],awaiting_guest_confirmation:['confirmed','admin_cancelled','expired'],confirmed:['payment_pending','paid','check_in_scheduled','admin_cancelled'],payment_pending:['paid','admin_cancelled'],paid:['check_in_scheduled','checked_in'],check_in_scheduled:['checked_in','no_show','admin_cancelled'],checked_in:['checked_out'],checked_out:['completed']};
  if(status!==previous&&!transitions[previous]?.includes(status))redirect(`/admin/stay/bookings/${id}?saved=invalid`);
  const admin=createSupabaseAdminClient();
  const {data:current}=await admin.from('stay_bookings').select('listing_id,subtotal,additional_guest_fee,cleaning_fee,discount_amount,total_amount,card_fee_rate,card_fee_amount,payment_status,paid_at,customer_id').eq('id',id).maybeSingle();
  if(!current)redirect(`/admin/stay/bookings/${id}?saved=failed`);
  if(checkIn!==previousCheckIn||checkOut!==previousCheckOut){
    const blockingStatuses=['pending_admin_review','awaiting_guest_confirmation','confirmed','payment_pending','paid','checked_in'];
    const [{count:bookingConflicts},{count:blockConflicts}]=await Promise.all([
      admin.from('stay_bookings').select('id',{count:'exact',head:true}).eq('listing_id',current.listing_id).neq('id',id).in('status',blockingStatuses).lt('check_in_date',checkOut).gt('check_out_date',checkIn),
      admin.from('stay_blocked_dates').select('id',{count:'exact',head:true}).eq('listing_id',current.listing_id).is('calendar_feed_id',null).lt('start_date',checkOut).gt('end_date',checkIn),
    ]);
    if((bookingConflicts??0)>0||(blockConflicts??0)>0)redirect(`/admin/stay/bookings/${id}?saved=conflict`);
  }
  const pricing=current.payment_status==='unpaid'?(()=>{const subtotal=num(formData,'subtotal'),additionalGuestFee=num(formData,'additionalGuestFee'),cleaningFee=num(formData,'cleaningFee'),discount=Math.min(num(formData,'discount'),subtotal+additionalGuestFee),totalAmount=num(formData,'totalAmount'),cardFeeRate=Math.min(100,num(formData,'cardFeeRate'));return{subtotal,additional_guest_fee:additionalGuestFee,cleaning_fee:cleaningFee,discount_amount:discount,total_amount:totalAmount,card_fee_rate:cardFeeRate,card_fee_amount:0}})():{subtotal:current.subtotal,additional_guest_fee:current.additional_guest_fee,cleaning_fee:current.cleaning_fee,discount_amount:current.discount_amount,total_amount:current.total_amount,card_fee_rate:current.card_fee_rate,card_fee_amount:current.card_fee_amount};
  const nights=Math.round((new Date(`${checkOut}T00:00:00Z`).getTime()-new Date(`${checkIn}T00:00:00Z`).getTime())/86400000);
  const update={check_in_date:checkIn,check_out_date:checkOut,nights,status,payment_status:paymentStatus,payment_method:paymentMethod||null,admin_message:text(formData,'adminMessage'),admin_memo:text(formData,'adminMemo',5000),...pricing,updated_at:new Date().toISOString(),...(status==='awaiting_guest_confirmation'?{admin_reviewed_at:new Date().toISOString()}:{}),...(paymentStatus==='paid'&&!current.paid_at?{paid_at:new Date().toISOString()}:{})};
  const {error}=await admin.from('stay_bookings').update(update).eq('id',id).eq('status',previous).eq('payment_status',current.payment_status).eq('check_in_date',previousCheckIn).eq('check_out_date',previousCheckOut);
  if(error)redirect(`/admin/stay/bookings/${id}?saved=failed`);
  if(status!==previous)await admin.from('stay_booking_status_history').insert({booking_id:id,previous_status:previous,new_status:status,changed_by_user_id:user.id,changed_by_role:'admin'});

  // 顧客へのメール送信
  const {data:bookingWithCustomer} = await admin.from('stay_bookings').select('stay_customers(name,email),booking_number').eq('id',id).single();
  if(bookingWithCustomer){
    const customer = bookingWithCustomer.stay_customers as unknown as {name: string, email: string};
    const subject = `【SK EC Pro】予約内容が変更されました（${bookingWithCustomer.booking_number}）`;
    const text = `${customer.name} 様\n\n予約内容が変更されました。\n${SITE_URL}/stay/mypage/bookings/${id}`;
    await notify(id, current.customer_id, customer.email, customer.name, bookingWithCustomer.booking_number, subject, text).catch(e=>console.error("予約変更通知に失敗しました。",e));
  }

  revalidatePath(`/admin/stay/bookings/${id}`);revalidatePath('/admin/stay/bookings');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search');revalidatePath(`/stay/mypage/bookings/${id}`);
  redirect(`/admin/stay/bookings/${id}?saved=success`);
}
export async function reassignStayBookingCustomer(formData:FormData){await requireAdminUser();const bookingId=text(formData,'bookingId',36),customerId=text(formData,'customerId',36);if(!bookingId||!customerId)redirect(`/admin/stay/bookings/${bookingId}?linked=invalid`);const {data,error}=await createSupabaseAdminClient().rpc('reassign_admin_stay_booking_customer',{p_booking_id:bookingId,p_customer_id:customerId});if(error||data!==true){console.error('宿泊予約を別の顧客へリンクできませんでした。',error);redirect(`/admin/stay/bookings/${bookingId}?linked=failed`)}revalidatePath(`/admin/stay/bookings/${bookingId}`);revalidatePath('/admin/stay/bookings');revalidatePath('/admin/stay/customers');revalidatePath('/admin/stay/messages');redirect(`/admin/stay/bookings/${bookingId}?linked=success`)}
export async function updateStaySettings(formData:FormData){await requireAdminUser();const percent=(name:string)=>Math.min(100,num(formData,name));const {error}=await createSupabaseAdminClient().from('stay_settings').update({weekly_discount_percent:percent('weeklyDiscount'),biweekly_discount_percent:percent('biweeklyDiscount'),monthly_discount_percent:percent('monthlyDiscount'),updated_at:new Date().toISOString()}).eq('id',true);if(error){console.error('宿泊割引設定を保存できませんでした。',error);redirect('/admin/stay/settings?saved=failed')}revalidatePath('/admin/stay/settings');revalidatePath('/stay/search');redirect('/admin/stay/settings?saved=success')}
export async function updateListing(formData:FormData){await requireAdminUser();const id=text(formData,'id',36);await createSupabaseAdminClient().from('stay_listings').update({name:text(formData,'name',100),base_price:num(formData,'basePrice'),base_guests:num(formData,'baseGuests'),max_guests:num(formData,'maxGuests'),additional_guest_price:num(formData,'additionalGuestPrice'),cleaning_fee:num(formData,'cleaningFee'),is_active:formData.get('isActive')==='on',is_public:formData.get('isPublic')==='on',booking_enabled:formData.get('bookingEnabled')==='on',updated_at:new Date().toISOString()}).eq('id',id);revalidatePath('/admin/stay/listings')}
const STAY_IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp']);const STAY_IMAGE_MAX_BYTES=10*1024*1024;
function imageExtension(file:File){if(file.type==='image/jpeg')return 'jpg';if(file.type==='image/png')return 'png';return 'webp'}
function validStayImage(value:FormDataEntryValue|null):value is File{return value instanceof File&&value.size>0&&value.size<=STAY_IMAGE_MAX_BYTES&&STAY_IMAGE_TYPES.has(value.type)}
export async function uploadStayListingImages(formData:FormData){await requireAdminUser();const listingId=text(formData,'listingId',36);const entries=formData.getAll('images'),files=entries.filter(validStayImage);if(!listingId||files.length===0||files.length!==entries.length)redirect('/admin/stay/listings?image=invalid');const admin=createSupabaseAdminClient();const {data:listing}=await admin.from('stay_listings').select('id,code').eq('id',listingId).maybeSingle();if(!listing)redirect('/admin/stay/listings?image=invalid');const {count}=await admin.from('stay_listing_images').select('id',{count:'exact',head:true}).eq('listing_id',listingId);let sortOrder=count??0;for(const file of files){const path=`listings/${listing.code}/${crypto.randomUUID()}.${imageExtension(file)}`;const {error:uploadError}=await admin.storage.from('stay-listings').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){console.error('宿泊リスティング画像のアップロードに失敗しました。',uploadError);redirect('/admin/stay/listings?image=upload_failed')}const {error:insertError}=await admin.from('stay_listing_images').insert({listing_id:listingId,storage_path:path,alt_text:`${listing.code} 宿泊施設`,sort_order:sortOrder,is_cover:sortOrder===0});if(insertError){await admin.storage.from('stay-listings').remove([path]);console.error('宿泊リスティング画像の保存に失敗しました。',insertError);redirect('/admin/stay/listings?image=save_failed')}sortOrder+=1}revalidatePath('/admin/stay/listings');revalidatePath('/stay/search');revalidatePath('/stay/listings');redirect('/admin/stay/listings?image=success')}
export async function uploadStayBuildingImage(formData:FormData){await requireAdminUser();const buildingCode=text(formData,'buildingCode',4),file=formData.get('image');if(!['F322','F321','F443'].includes(buildingCode)||!validStayImage(file))redirect('/admin/stay/listings?buildingImage=invalid');const admin=createSupabaseAdminClient();const {data:existing}=await admin.from('stay_building_images').select('storage_path').eq('building_code',buildingCode).maybeSingle();const path=`buildings/${buildingCode}/${crypto.randomUUID()}.${imageExtension(file)}`;const {error:uploadError}=await admin.storage.from('stay-listings').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){console.error('宿泊建物画像のアップロードに失敗しました。',uploadError);redirect('/admin/stay/listings?buildingImage=upload_failed')}const {error:saveError}=await admin.from('stay_building_images').upsert({building_code:buildingCode,storage_path:path,alt_text:`${buildingCode} 建物`,updated_at:new Date().toISOString()},{onConflict:'building_code'});if(saveError){await admin.storage.from('stay-listings').remove([path]);console.error('宿泊建物画像の保存に失敗しました。',saveError);redirect('/admin/stay/listings?buildingImage=save_failed')}if(existing?.storage_path)await admin.storage.from('stay-listings').remove([existing.storage_path]);revalidatePath('/admin/stay/listings');revalidatePath('/stay/search');redirect('/admin/stay/listings?buildingImage=success')}
export async function addBlockedDate(formData:FormData){const user=await requireAdminUser();await createSupabaseAdminClient().from('stay_blocked_dates').insert({listing_id:text(formData,'listingId',36),start_date:text(formData,'startDate',10),end_date:text(formData,'endDate',10),reason:text(formData,'reason',200),admin_memo:text(formData,'memo'),created_by:user.id});revalidatePath('/admin/stay/blocked-dates');revalidatePath('/admin/stay/calendar')}
export async function addPricingRule(formData:FormData){await requireAdminUser();await createSupabaseAdminClient().from('stay_pricing_rules').insert({listing_id:text(formData,'listingId',36)||null,name:text(formData,'name',100),rule_type:text(formData,'ruleType',30),start_date:text(formData,'startDate',10)||null,end_date:text(formData,'endDate',10)||null,specific_date:text(formData,'specificDate',10)||null,multiplier:Number(formData.get('multiplier'))||1,priority:num(formData,'priority')});revalidatePath('/admin/stay/pricing')}
export async function sendAdminStayMessage(formData:FormData){const user=await requireAdminUser();const threadId=text(formData,'threadId',36),body=text(formData,'body',5000);if(!threadId||!body)return;const admin=createSupabaseAdminClient();await admin.from('stay_messages').insert({thread_id:threadId,sender_user_id:user.id,sender_role:'admin',body});await admin.from('stay_message_threads').update({last_message_at:new Date().toISOString(),customer_unread_count:1,updated_at:new Date().toISOString()}).eq('id',threadId);revalidatePath(`/admin/stay/messages/${threadId}`)}

export async function saveStayCalendarFeed(formData:FormData){await requireAdminUser();const listingId=text(formData,'listingId',36);const feedUrl=validatedAirbnbCalendarUrl(text(formData,'feedUrl',2000));const name=text(formData,'calendarName',100)||'Airbnbカレンダー';if(!listingId||!feedUrl)redirect('/admin/stay/blocked-dates?ical=invalid');const admin=createSupabaseAdminClient();const {data:listing}=await admin.from('stay_listings').select('id,code').eq('id',listingId).maybeSingle();if(!listing)redirect('/admin/stay/blocked-dates?ical=invalid');const {data:existing,error:existingError}=await admin.from('stay_calendar_feeds').select('id').eq('listing_id',listingId).eq('feed_url',feedUrl).maybeSingle();if(existingError){console.error('AirbnbカレンダーURLの重複確認に失敗しました。',existingError);redirect('/admin/stay/blocked-dates?ical=save_failed')}const saved=existing?await admin.from('stay_calendar_feeds').update({name,is_enabled:true,updated_at:new Date().toISOString()}).eq('id',existing.id).select('id').single():await admin.from('stay_calendar_feeds').insert({listing_id:listingId,provider:'airbnb',name,feed_url:feedUrl,is_enabled:true}).select('id').single();const {data:feed,error}=saved;if(error||!feed){console.error('AirbnbカレンダーURLを保存できませんでした。',error);redirect('/admin/stay/blocked-dates?ical=save_failed')}let count:number;try{count=await syncStayCalendarFeedById(feed.id)}catch(error){console.error('Airbnbカレンダー同期に失敗しました。',error);redirect('/admin/stay/blocked-dates?ical=sync_failed')}revalidatePath('/admin/stay/blocked-dates');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search');redirect(`/admin/stay/blocked-dates?ical=success&count=${count}`)}

export async function syncStayCalendarFeed(formData:FormData){await requireAdminUser();const feedId=text(formData,'feedId',36);if(!feedId)redirect('/admin/stay/blocked-dates?ical=invalid');let count:number;try{count=await syncStayCalendarFeedById(feedId)}catch(error){console.error('Airbnbカレンダー同期に失敗しました。',error);redirect('/admin/stay/blocked-dates?ical=sync_failed')}revalidatePath('/admin/stay/blocked-dates');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search');redirect(`/admin/stay/blocked-dates?ical=success&count=${count}`)}
export async function updateStayCalendarFeed(formData:FormData){await requireAdminUser();const feedId=text(formData,'feedId',36),listingId=text(formData,'listingId',36),feedUrl=validatedAirbnbCalendarUrl(text(formData,'feedUrl',2000)),name=text(formData,'calendarName',100)||'Airbnbカレンダー';if(!feedId||!listingId||!feedUrl)redirect('/admin/stay/blocked-dates?ical=invalid');const admin=createSupabaseAdminClient();const {data:duplicate,error:duplicateError}=await admin.from('stay_calendar_feeds').select('id').eq('listing_id',listingId).eq('feed_url',feedUrl).neq('id',feedId).maybeSingle();if(duplicateError||duplicate)redirect('/admin/stay/blocked-dates?ical=save_failed');const {error}=await admin.from('stay_calendar_feeds').update({listing_id:listingId,name,feed_url:feedUrl,is_enabled:true,updated_at:new Date().toISOString()}).eq('id',feedId);if(error){console.error('Airbnbカレンダー連携を更新できませんでした。',error);redirect('/admin/stay/blocked-dates?ical=save_failed')}let count:number;try{count=await syncStayCalendarFeedById(feedId)}catch(syncError){console.error('更新したAirbnbカレンダーの同期に失敗しました。',syncError);redirect('/admin/stay/blocked-dates?ical=sync_failed')}revalidatePath('/admin/stay/blocked-dates');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search');redirect(`/admin/stay/blocked-dates?ical=success&count=${count}`)}
export async function deleteStayCalendarFeed(formData:FormData){await requireAdminUser();const feedId=text(formData,'feedId',36);if(!feedId)return;const {error}=await createSupabaseAdminClient().from('stay_calendar_feeds').delete().eq('id',feedId);if(error)console.error('Airbnbカレンダー連携を削除できませんでした。',error);revalidatePath('/admin/stay/blocked-dates');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search')}

export async function deleteStayBooking(formData:FormData){const user=await requireAdminUser();const id=text(formData,'id',36);if(!id)return;const admin=createSupabaseAdminClient();const {data:booking}=await admin.from('stay_bookings').select('status').eq('id',id).maybeSingle();if(!booking)return;const deletable=['guest_cancelled','admin_cancelled','expired','no_show'];if(!deletable.includes(booking.status)){console.error('キャンセル済み以外の予約は削除できません。');return}const {error}=await admin.from('stay_bookings').delete().eq('id',id).in('status',deletable);if(error){console.error('宿泊予約の削除に失敗しました。',error);redirect(`/admin/stay/bookings/${id}?deleted=failed`)}revalidatePath('/admin/stay/bookings');revalidatePath('/admin/stay/calendar');revalidatePath('/stay/search');redirect('/admin/stay/bookings?deleted=success')}