import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { requireStayUser } from "@/lib/stay/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { yen } from "@/lib/stay/presentation";

const labels:Record<string,string>={admin_reviewing:"管理者確認中",awaiting_guest_confirmation:"顧客確認中",confirmed:"予約確定",payment_pending:"支払い待ち",paid:"支払い済み",completed:"完了",customer_cancelled:"顧客キャンセル",admin_cancelled:"管理者キャンセル"};
export default async function RideBookingsPage({searchParams}:{searchParams:Promise<{created?:string}>}){const {customer}=await requireStayUser("/stay/mypage/rides"),params=await searchParams;const {data:rows}=await createSupabaseAdminClient().from("stay_ride_bookings").select("*").eq("customer_id",customer.id).order("ride_date",{ascending:false}).order("departure_time",{ascending:false});return <><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Ride Bookings</p><h1 className="mt-2 text-3xl font-bold">配車予約</h1></div><Button asChild><Link href="/stay/mypage/rides/new">新しい配車予約</Link></Button></div>{params.created&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">配車予約を受け付けました。</p>}<div className="mt-6 grid gap-4">{(rows??[]).map(row=><Card key={row.id}><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-emerald-600">{row.booking_number}</p><h2 className="mt-1 text-lg font-bold">{row.ride_date} {String(row.departure_time).slice(0,5)}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{labels[row.status]??row.status}</span></div><p className="mt-4 text-sm"><span className="text-slate-500">出発：</span>{row.pickup_address}</p><p className="mt-2 text-sm"><span className="text-slate-500">到着：</span>{row.destination_address}</p><div className="mt-4 flex items-center justify-between gap-3"><p className="font-bold text-emerald-700">見積合計 {yen(row.total_amount)}</p><Button asChild variant="outline" size="sm"><Link href={`/stay/mypage/rides/${row.id}`}>詳細</Link></Button></div></CardContent></Card>)}{!rows?.length&&<p className="rounded-xl bg-white p-8 text-center text-slate-500">配車予約はまだありません。</p>}</div></>}
