import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { updateListing, uploadStayBuildingImage, uploadStayListingImages } from "../actions";

const buildings = ["F322", "F321", "F443"];

export default async function ListingsAdmin({ searchParams }: { searchParams: Promise<{ image?: string; buildingImage?: string }> }) {
  const q = await searchParams;
  const admin = createSupabaseAdminClient();
  const [{ data: rows }, { data: listingImages }, { data: buildingImages }] = await Promise.all([
    admin.from("stay_listings").select("*").order("sort_order"),
    admin.from("stay_listing_images").select("id,listing_id,storage_path,is_cover,sort_order").order("sort_order"),
    admin.from("stay_building_images").select("building_code,storage_path"),
  ]);
  const publicUrl = (path: string) => admin.storage.from("stay-listings").getPublicUrl(path).data.publicUrl;
  return <><h1 className="text-3xl font-bold">リスティング管理</h1>
    {(q.image === "success" || q.buildingImage === "success") && <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">画像を登録しました。</p>}
    {((q.image && q.image !== "success") || (q.buildingImage && q.buildingImage !== "success")) && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">画像を登録できませんでした。JPEG・PNG・WebP（10MB以下）を選択してください。</p>}
    <section className="mt-6"><h2 className="text-xl font-bold">建物画像</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{buildings.map((code) => { const current = buildingImages?.find((item) => item.building_code === code); return <div key={code} className="rounded-xl bg-white p-5"><h3 className="font-bold">{code}</h3><div className="mt-3 aspect-[16/9] rounded-lg bg-cover bg-center bg-slate-100" style={current ? { backgroundImage: `url(${publicUrl(current.storage_path)})` } : undefined}>{!current && <span className="grid h-full place-items-center text-sm text-slate-400">画像未登録</span>}</div><form action={uploadStayBuildingImage} className="mt-4 grid gap-3"><input type="hidden" name="buildingCode" value={code}/><Input type="file" name="image" accept="image/jpeg,image/png,image/webp" required/><Button size="sm">{current ? "画像を変更" : "画像を登録"}</Button></form></div> })}</div></section>
    <section className="mt-9"><h2 className="text-xl font-bold">部屋・全館リスティング</h2><div className="mt-4 grid gap-4">{(rows ?? []).map((listing) => { const images = listingImages?.filter((image) => image.listing_id === listing.id) ?? []; return <div key={listing.id} className="rounded-xl bg-white p-5"><form action={updateListing} className="grid gap-3 lg:grid-cols-7"><input type="hidden" name="id" value={listing.id}/><label className="font-bold">{listing.code}<Input name="name" defaultValue={listing.name}/></label><label>基本料金<Input name="basePrice" type="number" defaultValue={listing.base_price}/></label><label>基本人数<Input name="baseGuests" type="number" defaultValue={listing.base_guests}/></label><label>最大人数<Input name="maxGuests" type="number" defaultValue={listing.max_guests}/></label><label>追加/人泊<Input name="additionalGuestPrice" type="number" defaultValue={listing.additional_guest_price}/></label><label>清掃費<Input name="cleaningFee" type="number" defaultValue={listing.cleaning_fee}/></label><div className="space-y-2 text-xs"><label className="block"><input type="checkbox" name="isActive" defaultChecked={listing.is_active}/> 有効</label><label className="block"><input type="checkbox" name="isPublic" defaultChecked={listing.is_public}/> 公開</label><label className="block"><input type="checkbox" name="bookingEnabled" defaultChecked={listing.booking_enabled}/> 予約受付</label><Button size="sm">保存</Button></div></form><div className="mt-5 border-t pt-5"><div className="flex gap-3 overflow-x-auto">{images.map((image) => <div key={image.id} className="relative h-24 w-36 shrink-0 rounded-lg bg-cover bg-center bg-slate-100" style={{ backgroundImage: `url(${publicUrl(image.storage_path)})` }}>{image.is_cover && <span className="absolute left-2 top-2 rounded bg-emerald-600 px-2 py-1 text-[10px] font-bold text-white">メイン</span>}</div>)}{images.length === 0 && <p className="text-sm text-slate-400">画像未登録</p>}</div><form action={uploadStayListingImages} className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><input type="hidden" name="listingId" value={listing.id}/><label className="min-w-0 flex-1 text-sm">画像を追加（複数選択可）<Input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple required/></label><Button size="sm">アップロード</Button></form></div></div> })}</div></section>
  </>;
}
